# Generated by Django 4.1.1 on 2022-10-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_label_alter_label_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
